// <auto-generated />
namespace FFCJardinagens.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Shopping_Cart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Shopping_Cart));
        
        string IMigrationMetadata.Id
        {
            get { return "201711031812161_Shopping_Cart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
